version: "3"

services:
  tarantool:
    build: 
      context: .
    working_dir: /app/app
    command: tarantool init.lua

    volumes:
      - ./:/app
      - ./data:/var/lib/tarantool
  web:
    image: nginx
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - tarantool
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
